In [1]:
import pandas as pd
import os

data_path = 'output/analytics/data/'

dfs = {
    f.replace('.csv', ''): pd.read_csv(os.path.join(data_path, f))
    for f in os.listdir(data_path)
    if f.endswith('.csv')
}

In [2]:
for name, df in dfs.items():
    globals()[name] = df

In [3]:
for name, df in dfs.items():
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    print("\n--- HEAD ---")
    print(df.head())

============================================================
  fact_maintenance_detail
============================================================

--- HEAD ---
    detail_id maintenance_job_id        date aircraft_id facility_id  \
0  MD-0000001          MJ-000001  2023-01-19      AC-001     FAC-PSM
1  MD-0000002          MJ-000001  2023-01-19      AC-001     FAC-PSM
2  MD-0000003          MJ-000002  2023-02-08      AC-001     FAC-PSM
3  MD-0000004          MJ-000002  2023-02-08      AC-001     FAC-PSM
4  MD-0000005          MJ-000002  2023-02-08      AC-001     FAC-PSM

  action_type  cost_category  jasc_ata_code  \
0      REPAIR          LABOR         7200.0
1     REPLACE          PARTS         7200.0
2     INSPECT          LABOR            NaN
3     CERTIFY  CERTIFICATION            NaN
4     SERVICE           FUEL            NaN

                           part_description      uom  quantity  unit_cost  \
0  Engine (General) - COMPONENT_REPLACEMENT    Hours      21.8      115.0
1                          Engine (General)     Each       3.0    17630.0
2                          Inspection Labor    Hours      21.0      115.0
3                      IA Return-to-Service    Hours       1.9      135.0
4                   Jet-A Fuel (ground run)  Gallons      34.5        6.8

   extended_cost
0         2507.0
1        52890.0
2         2415.0
3          256.5
4          234.6

============================================================
  dim_facility
============================================================

--- HEAD ---
  facility_id          facility_name  icao state       type  technician_count  \
0     FAC-PSM  Portsmouth NH (Pease)  KPSM    NH    PRIMARY                28
1     FAC-BVU        Boulder City NV  KBVU    NV  SECONDARY                12

   maintenance_bays
0                 8
1                 4

============================================================
  dim_aircraft
============================================================

--- HEAD ---
  aircraft_id tail_number      model engine_type  engine_count serial_number  \
0      AC-001      N100AF  PC-12 NGX    PT6A-67P             1     PC12-1700
1      AC-002      N101AF  PC-12 NGX    PT6A-67P             1     PC12-1701
2      AC-003      N102AF  PC-12 NGX    PT6A-67P             1     PC12-1702
3      AC-004      N103AF  PC-12 NGX    PT6A-67P             1     PC12-1703
4      AC-005      N104AF  PC-12 NGX    PT6A-67P             1     PC12-1704

  delivery_date  years_in_service base_facility_id     region  seat_capacity  \
0       1/24/21               4.9          FAC-PSM  Northeast             10
1        4/5/19               6.7          FAC-PSM  Northeast             10
2      11/24/22               3.1          FAC-PSM  Northeast             10
3       2/19/23               2.9          FAC-PSM  Northeast             10
4        1/3/20               6.0          FAC-PSM  Northeast             10

   max_range_nm  mtow_kg current_status maintenance_program
0          1845     4740         ACTIVE    PHASE_INSPECTION
1          1845     4740         ACTIVE    PHASE_INSPECTION
2          1845     4740         ACTIVE    PHASE_INSPECTION
3          1845     4740         ACTIVE    PHASE_INSPECTION
4          1845     4740         ACTIVE    PHASE_INSPECTION

============================================================
  dim_crew
============================================================

--- HEAD ---
    crew_id         crew_name           role base_facility_id type_ratings
0  CREW-001       Mark Garcia        Captain          FAC-PSM  PC-12,PC-24
1  CREW-002    Sarah Anderson        Captain          FAC-PSM  PC-12,PC-24
2  CREW-003     Joseph Miller  First Officer          FAC-PSM  PC-12,PC-24
3  CREW-004  Timothy Martinez        Captain          FAC-PSM  PC-12,PC-24
4  CREW-005      Amanda Lopez        Captain          FAC-PSM  PC-12,PC-24

============================================================
  fact_flight
============================================================

--- HEAD ---
     flight_id        date aircraft_id tail_number      model  owner_id  \
0  FLT-0000001  2023-01-01      AC-001      N100AF  PC-12 NGX  OWN-0005
1  FLT-0000002  2023-01-01      AC-001      N100AF  PC-12 NGX       NaN
2  FLT-0000003  2023-01-02      AC-001      N100AF  PC-12 NGX  OWN-0307
3  FLT-0000004  2023-01-02      AC-001      N100AF  PC-12 NGX  OWN-0247
4  FLT-0000005  2023-01-03      AC-001      N100AF  PC-12 NGX  OWN-0246

   booking_id  journey_leg_seq origin_icao destination_icao  ...  \
0  BK-0000001                1        KJFK             KPWM  ...
1         NaN                1        KSFM             KPSM  ...
2  BK-0000003                1        KBED             KTEB  ...
3  BK-0000004                1        KPSM             KBDL  ...
4  BK-0000005                1        KPWM             KMVY  ...

  flight_purpose is_deadhead  is_maintenance_ferry  flight_status  \
0        Leisure           0                     0      COMPLETED
1  Repositioning           1                     0      COMPLETED
2       Business           0                     0      COMPLETED
3       Business           0                     0      COMPLETED
4        Leisure           0                     0      COMPLETED

   fuel_consumed_gal  weather_delay_min  pilot_id  copilot_id  season  \
0               59.8                  0  CREW-015         NaN  Winter
1                4.8                  0  CREW-070         NaN  Winter
2               40.1                  0  CREW-069    CREW-009  Winter
3               27.2                  0  CREW-010         NaN  Winter
4               34.0                  0  CREW-041    CREW-016  Winter

  day_of_week
0           7
1           7
2           1
3           1
4           2

[5 rows x 26 columns]

============================================================
  fact_aircraft_daily_status
============================================================

--- HEAD ---
  aircraft_id    date  status  flight_hours  flight_cycles maintenance_type
0      AC-001  1/1/23  FLYING          2.52              2              NaN
1      AC-001  1/2/23  FLYING          1.64              2              NaN
2      AC-001  1/3/23  FLYING          2.71              2              NaN
3      AC-001  1/4/23  FLYING          3.18              3              NaN
4      AC-001  1/5/23  FLYING          2.89              2              NaN

============================================================
  fact_maintenance_job
============================================================

--- HEAD ---
  maintenance_job_id     date aircraft_id tail_number facility_id  \
0          MJ-000001  1/19/23      AC-001      N100AF     FAC-PSM
1          MJ-000002   2/8/23      AC-001      N100AF     FAC-PSM
2          MJ-000003  3/22/23      AC-001      N100AF     FAC-PSM
3          MJ-000004  3/22/23      AC-001      N100AF     FAC-PSM
4          MJ-000005   5/3/23      AC-001      N100AF     FAC-PSM

        maintenance_type  is_scheduled  severity trigger_source job_status  \
0  COMPONENT_REPLACEMENT             0  MODERATE   PILOT_REPORT  COMPLETED
1             INSPECTION             1   ROUTINE      SCHEDULED  COMPLETED
2             INSPECTION             1   ROUTINE      SCHEDULED  COMPLETED
3             INSPECTION             1   ROUTINE      SCHEDULED  COMPLETED
4             INSPECTION             1   ROUTINE      SCHEDULED  COMPLETED

  start_datetime close_datetime  total_elapsed_hours          finding_code  \
0  1/19/23 20:00   1/20/23 8:29                 12.5      Engine (General)
1    2/8/23 7:00   2/8/23 17:13                 10.2            NO_FINDING
2   3/22/23 7:00  3/22/23 19:16                 12.3            NO_FINDING
3   3/22/23 7:00  3/23/23 13:13                 30.2            NO_FINDING
4    5/3/23 7:00   5/3/23 20:32                 13.5  REPLACEMENT_REQUIRED

  technician_id  aircraft_hours_at_event
0      TECH-025                     50.8
1      TECH-030                    100.3
2      TECH-025                    200.5
3      TECH-012                    200.5
4      TECH-007                    301.0

============================================================
  dim_component
============================================================

--- HEAD ---
  component_id  jasc_ata_code      system_name         component_name  \
0    COMP-2752           2752  Flight Controls  Rudder Control System
1    COMP-7200           7200           Engine       Engine (General)
2    COMP-2750           2750  Flight Controls  Flight Control System
3    COMP-3242           3242     Landing Gear         Brake Assembly
4    COMP-2497           2497        Empennage    Stabilizer Assembly

   sdrs_weight_pc12  sdrs_weight_pc24
0              0.08              0.03
1              0.07              0.05
2              0.07              0.04
3              0.05              0.07
4              0.04              0.02

============================================================
  dim_date
============================================================

--- HEAD ---
   date_key        date  day day_of_week  day_of_week_num  is_weekend  \
0  20230101  2023-01-01    1      Sunday                7           1
1  20230102  2023-01-02    2      Monday                1           0
2  20230103  2023-01-03    3     Tuesday                2           0
3  20230104  2023-01-04    4   Wednesday                3           0
4  20230105  2023-01-05    5    Thursday                4           0

   week_num  month month_name  quarter  year  season  is_holiday  fiscal_year
0        52      1    January        1  2023  Winter           1         2022
1         1      1    January        1  2023  Winter           0         2022
2         1      1    January        1  2023  Winter           0         2022
3         1      1    January        1  2023  Winter           0         2022
4         1      1    January        1  2023  Winter           0         2022

============================================================
  dim_owner
============================================================

--- HEAD ---
   owner_id       owner_name        region state  share_type  \
0  OWN-0001      James Patel       Midwest    MI  Share_1/16
1  OWN-0002   James Williams     Southeast    TN  Share_1/16
2  OWN-0003  Daniel Thompson     Northeast    RI   Share_1/8
3  OWN-0004   Rebecca Wright  Mid-Atlantic    PA   Share_1/8
4  OWN-0005     Nicole Clark  Mid-Atlantic    VA  Share_1/16

   annual_hours_contracted   join_date  tenure_years aircraft_preference  \
0                       50  2019-11-07           6.1               PC-12
1                       50  2020-01-04           6.0       No Preference
2                      200  2023-06-14           2.5               PC-24
3                      200  2024-11-24           1.1       No Preference
4                      100  2024-12-10           1.1               PC-12

   cobalt_pass_holder  jetfly_access  status  owner_type
0                   0              0  ACTIVE      Family
1                   0              0  ACTIVE      Family
2                   0              0  ACTIVE   Corporate
3                   0              1  ACTIVE   Corporate
4                   0              0  ACTIVE  Individual

============================================================
  fact_booking
============================================================

--- HEAD ---
   booking_id booking_date  owner_id  passenger_count  pet_count  \
0  BK-0000001   2022-12-24  OWN-0005                7          0
1  BK-0000003   2022-12-22  OWN-0307                4          0
2  BK-0000004   2022-12-22  OWN-0247                3          0
3  BK-0000005   2022-12-30  OWN-0246                1          0
4  BK-0000007   2022-12-25  OWN-0167                1          0

  preferred_model departure_date origin_icao destination_icao trip_purpose  \
0           PC-12     2023-01-01        KJFK             KPWM      Leisure
1           PC-12     2023-01-02        KBED             KTEB     Business
2           PC-24     2023-01-02        KPSM             KBDL     Business
3           PC-12     2023-01-03        KPWM             KMVY      Leisure
4           PC-12     2023-01-04        KPSM             KTEB     Business

  booking_status booking_channel  lead_time_days
0      COMPLETED           Phone               8
1      COMPLETED      Mobile App              11
2      COMPLETED    Owner Portal              11
3      COMPLETED    Owner Portal               4
4      COMPLETED    Owner Portal              10

============================================================
  dim_airport
============================================================

--- HEAD ---
  airport_icao     airport_name        city state     region  \
0         KPSM  Portsmouth Intl  Portsmouth    NH  Northeast
1         KBOS     Boston Logan      Boston    MA  Northeast
2         KJFK   John F Kennedy    New York    NY  Northeast
3         KEWR   Newark Liberty      Newark    NJ  Northeast
4         KPVD       T.F. Green  Providence    RI  Northeast

   runway_length_ft runway_surface  pc12_accessible  pc24_accessible  \
0             11321           ASPH                1                1
1             10083           ASPH                1                1
2             14511           ASPH                1                1
3             11000           ASPH                1                1
4              7166           ASPH                1                1

   latitude  longitude
0   43.0779   -70.8233
1   42.3620   -71.0079
2   40.6394   -73.7793
3   40.6925   -74.1687
4   41.7250   -71.4257

In [4]:
for name, df in dfs.items():
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    print("\n--- TAIL ---")
    print(df.tail())

============================================================
  fact_maintenance_detail
============================================================

--- TAIL ---
        detail_id maintenance_job_id        date aircraft_id facility_id  \
16098  MD-0016099          MJ-001059  2025-12-07      AC-026     FAC-PSM
16099  MD-0016100          MJ-001803  2023-02-10      AC-044     FAC-BVU
16100  MD-0016101          MJ-001680  2023-12-31      AC-041     FAC-BVU
16101  MD-0016102          MJ-001462  2024-03-13      AC-036     FAC-BVU
16102  MD-0016103          MJ-001608  2025-02-06      AC-039     FAC-BVU

      action_type cost_category  jasc_ata_code         part_description   uom  \
16098     REPLACE         PARTS         2390.0  Audio Management System  Each
16099     REPLACE         PARTS         2390.0  Audio Management System  Each
16100     REPLACE         PARTS         2390.0  Audio Management System  Each
16101     REPLACE         PARTS         2390.0  Audio Management System  Each
16102     REPLACE         PARTS         2390.0  Audio Management System  Each

       quantity  unit_cost  extended_cost
16098       1.0     7044.0         7044.0
16099       1.0     3765.0         3765.0
16100       1.0     3964.0         3964.0
16101       1.0     6703.0         6703.0
16102       1.0     4742.0         4742.0

============================================================
  dim_facility
============================================================

--- TAIL ---
  facility_id          facility_name  icao state       type  technician_count  \
0     FAC-PSM  Portsmouth NH (Pease)  KPSM    NH    PRIMARY                28
1     FAC-BVU        Boulder City NV  KBVU    NV  SECONDARY                12

   maintenance_bays
0                 8
1                 4

============================================================
  dim_aircraft
============================================================

--- TAIL ---
   aircraft_id tail_number  model engine_type  engine_count serial_number  \
57      AC-058      N811AF  PC-24     FJ44-4A             2      PC24-211
58      AC-059      N812AF  PC-24     FJ44-4A             2      PC24-212
59      AC-060      N813AF  PC-24     FJ44-4A             2      PC24-213
60      AC-061      N814AF  PC-24     FJ44-4A             2      PC24-214
61      AC-062      N815AF  PC-24     FJ44-4A             2      PC24-215

   delivery_date  years_in_service base_facility_id region  seat_capacity  \
57        5/8/24               1.6          FAC-BVU   West             11
58       10/3/18               7.2          FAC-BVU   West             11
59       8/27/19               6.3          FAC-BVU   West             11
60       9/25/19               6.3          FAC-BVU   West             11
61      11/16/19               6.1          FAC-BVU   West             11

    max_range_nm  mtow_kg current_status maintenance_program
57          2000     8300         ACTIVE    PHASE_INSPECTION
58          2000     8300         ACTIVE    PHASE_INSPECTION
59          2000     8300         ACTIVE    PHASE_INSPECTION
60          2000     8300         ACTIVE    PHASE_INSPECTION
61          2000     8300         ACTIVE    PHASE_INSPECTION

============================================================
  dim_crew
============================================================

--- TAIL ---
      crew_id       crew_name          role base_facility_id type_ratings
115  TECH-036   Timothy Brown  A&P Mechanic          FAC-BVU  PC-12,PC-24
116  TECH-037  Amanda Johnson  IA Inspector          FAC-BVU  PC-12,PC-24
117  TECH-038     Karen Davis  A&P Mechanic          FAC-BVU  PC-12,PC-24
118  TECH-039   Joseph Thomas  A&P Mechanic          FAC-BVU  PC-12,PC-24
119  TECH-040  Emily Martinez  A&P Mechanic          FAC-BVU  PC-12,PC-24

============================================================
  fact_flight
============================================================

--- TAIL ---
          flight_id        date aircraft_id tail_number  model  owner_id  \
142836  FLT-0142837  2025-12-30      AC-062      N815AF  PC-24  OWN-0259
142837  FLT-0142838  2025-12-30      AC-062      N815AF  PC-24       NaN
142838  FLT-0142839  2025-12-30      AC-062      N815AF  PC-24  OWN-0241
142839  FLT-0142840  2025-12-31      AC-062      N815AF  PC-24  OWN-0326
142840  FLT-0142841  2025-12-31      AC-062      N815AF  PC-24  OWN-0023

        booking_id  journey_leg_seq origin_icao destination_icao  ...  \
142836  BK-0142837                1        KEWR             KJFK  ...
142837         NaN                1        KSFM             KPSM  ...
142838  BK-0142839                1        KMVY             KPBI  ...
142839  BK-0142840                1        KATL             KJFK  ...
142840  BK-0142841                1        KBOS             KTPA  ...

       flight_purpose is_deadhead  is_maintenance_ferry  flight_status  \
142836       Business           0                     0      COMPLETED
142837  Repositioning           1                     0      COMPLETED
142838        Leisure           0                     0      COMPLETED
142839        Medical           0                     0      COMPLETED
142840       Business           0                     0      COMPLETED

        fuel_consumed_gal  weather_delay_min  pilot_id  copilot_id  season  \
142836                4.8                  0  CREW-051    CREW-032  Winter
142837                5.7                  0  CREW-068    CREW-035  Winter
142838              279.3                  0  CREW-022    CREW-009  Winter
142839              184.3                  0  CREW-072    CREW-043  Winter
142840              287.8                  0  CREW-007    CREW-074  Winter

       day_of_week
142836           2
142837           2
142838           2
142839           3
142840           3

[5 rows x 26 columns]

============================================================
  fact_aircraft_daily_status
============================================================

--- TAIL ---
      aircraft_id      date     status  flight_hours  flight_cycles  \
63075      AC-062  12/27/25     FLYING          2.87              2
63076      AC-062  12/28/25     FLYING          3.44              2
63077      AC-062  12/29/25  AVAILABLE          0.00              0
63078      AC-062  12/30/25     FLYING          5.80              4
63079      AC-062  12/31/25     FLYING          2.81              2

      maintenance_type
63075              NaN
63076              NaN
63077              NaN
63078              NaN
63079              NaN

============================================================
  fact_maintenance_job
============================================================

--- TAIL ---
     maintenance_job_id      date aircraft_id tail_number facility_id  \
2584          MJ-002585   9/20/25      AC-062      N815AF     FAC-BVU
2585          MJ-002586   9/23/25      AC-062      N815AF     FAC-BVU
2586          MJ-002587   11/3/25      AC-062      N815AF     FAC-BVU
2587          MJ-002588  12/10/25      AC-062      N815AF     FAC-BVU
2588          MJ-002589  12/13/25      AC-062      N815AF     FAC-BVU

     maintenance_type  is_scheduled severity trigger_source job_status  \
2584       INSPECTION             1  ROUTINE      SCHEDULED  COMPLETED
2585       INSPECTION             1  ROUTINE      SCHEDULED  COMPLETED
2586       INSPECTION             1  ROUTINE      SCHEDULED  COMPLETED
2587       INSPECTION             1  ROUTINE      SCHEDULED  COMPLETED
2588       INSPECTION             1  ROUTINE      SCHEDULED  COMPLETED

     start_datetime  close_datetime  total_elapsed_hours        finding_code  \
2584   9/20/25 7:00    9/21/25 5:04                 22.1        MINOR_DEFECT
2585   9/23/25 7:00   9/23/25 22:39                 15.7  WEAR_WITHIN_LIMITS
2586   11/3/25 7:00   11/3/25 16:05                  9.1          NO_FINDING
2587  12/10/25 7:00  12/11/25 10:16                 27.3          NO_FINDING
2588  12/13/25 7:00   12/14/25 1:43                 18.7        MINOR_DEFECT

     technician_id  aircraft_hours_at_event
2584      TECH-038                   2814.0
2585      TECH-015                   2820.5
2586      TECH-009                   2922.3
2587      TECH-014                   3015.7
2588      TECH-002                   3023.8

============================================================
  dim_component
============================================================

--- TAIL ---
   component_id  jasc_ata_code system_name        component_name  \
39    COMP-6120           6120   Propeller    Propeller Governor
40    COMP-7310           7310      Engine  Fuel Nozzle Assembly
41    COMP-7400           7400      Engine       Ignition System
42    COMP-7510           7510      Engine    Engine Bleed Valve
43    COMP-7910           7910      Engine     Engine Oil System

    sdrs_weight_pc12  sdrs_weight_pc24
39              0.04              0.00
40              0.04              0.03
41              0.03              0.03
42              0.03              0.03
43              0.03              0.03

============================================================
  dim_date
============================================================

--- TAIL ---
      date_key        date  day day_of_week  day_of_week_num  is_weekend  \
1091  20251227  2025-12-27   27    Saturday                6           1
1092  20251228  2025-12-28   28      Sunday                7           1
1093  20251229  2025-12-29   29      Monday                1           0
1094  20251230  2025-12-30   30     Tuesday                2           0
1095  20251231  2025-12-31   31   Wednesday                3           0

      week_num  month month_name  quarter  year  season  is_holiday  \
1091        52     12   December        4  2025  Winter           0
1092        52     12   December        4  2025  Winter           0
1093         1     12   December        4  2025  Winter           0
1094         1     12   December        4  2025  Winter           0
1095         1     12   December        4  2025  Winter           1

      fiscal_year
1091         2025
1092         2025
1093         2025
1094         2025
1095         2025

============================================================
  dim_owner
============================================================

--- TAIL ---
     owner_id         owner_name        region state  share_type  \
345  OWN-0346      Heather Lewis       Midwest    OH  Share_1/16
346  OWN-0347   William Anderson     Southeast    SC   Share_1/4
347  OWN-0348  Michelle Martinez     Northeast    MA  Share_1/16
348  OWN-0349        Rachel King  Mid-Atlantic    DC  Share_1/16
349  OWN-0350       Daniel Patel     Southeast    TN  Share_1/16

     annual_hours_contracted   join_date  tenure_years aircraft_preference  \
345                       50  2016-12-09           9.1               PC-12
346                      400  2022-10-07           3.2               PC-24
347                      100  2022-07-02           3.5               PC-12
348                       50  2016-06-20           9.5               PC-12
349                      100  2023-09-08           2.3       No Preference

     cobalt_pass_holder  jetfly_access  status  owner_type
345                   0              0  ACTIVE      Family
346                   0              0  ACTIVE   Corporate
347                   0              0  ACTIVE  Individual
348                   0              0  ACTIVE      Family
349                   0              0  ACTIVE  Individual

============================================================
  fact_booking
============================================================

--- TAIL ---
        booking_id booking_date  owner_id  passenger_count  pet_count  \
123555  BK-C005879   2025-08-26  OWN-0214                4          0
123556  BK-C005880   2024-04-22  OWN-0262                5          0
123557  BK-C005881   2024-03-25  OWN-0029                2          0
123558  BK-C005882   2024-06-21  OWN-0042                2          0
123559  BK-C005883   2023-01-17  OWN-0055                5          0

       preferred_model departure_date origin_icao destination_icao  \
123555           PC-12     2025-09-05        KPBI             KLAX
123556           PC-12     2024-04-25        KLAS             K1B1
123557   No Preference     2024-03-30        KJFK             KMIA
123558           PC-12     2024-06-23        KBED             KPBI
123559           PC-24     2023-01-19        KIAD             KMHT

       trip_purpose booking_status  booking_channel  lead_time_days
123555        Mixed      CANCELLED       Mobile App              10
123556      Leisure        NO_SHOW       Mobile App               3
123557        Mixed        NO_SHOW       Mobile App               5
123558     Business        NO_SHOW     Owner Portal               2
123559     Business      CANCELLED  Account Manager               2

============================================================
  dim_airport
============================================================

--- TAIL ---
   airport_icao         airport_name         city state     region  \
29         KORD          O'Hare Intl      Chicago    IL    Midwest
30         KMSP  Minneapolis-St Paul  Minneapolis    MN    Midwest
31          2B2          Plum Island  Newburyport    MA  Northeast
32         K1B1               Hudson       Hudson    NY  Northeast
33         KSFM     Sanford Seacoast      Sanford    ME  Northeast

    runway_length_ft runway_surface  pc12_accessible  pc24_accessible  \
29             13000           CONC                1                1
30             11006           CONC                1                1
31              2700           ASPH                1                0
32              3600           ASPH                1                0
33              5200           ASPH                1                1

    latitude  longitude
29   41.9786   -87.9048
30   44.8801   -93.2217
31   42.7959   -70.8412
32   42.2913   -73.7103
33   43.3939   -70.7080

In [5]:
for name, df in dfs.items():
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    print("\n--- INFO ---")
    df.info()

============================================================
  fact_maintenance_detail
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16103 entries, 0 to 16102
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   detail_id           16103 non-null  object
 1   maintenance_job_id  16103 non-null  object
 2   date                16103 non-null  object
 3   aircraft_id         16103 non-null  object
 4   facility_id         16103 non-null  object
 5   action_type         16103 non-null  object
 6   cost_category       16103 non-null  object
 7   jasc_ata_code       2423 non-null   float64
 8   part_description    16103 non-null  object
 9   uom                 16103 non-null  object
 10  quantity            16103 non-null  float64
 11  unit_cost           16103 non-null  float64
 12  extended_cost       16103 non-null  float64
dtypes: float64(4), object(9)
memory usage: 1.6+ MB

============================================================
  dim_facility
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   facility_id       2 non-null      object
 1   facility_name     2 non-null      object
 2   icao              2 non-null      object
 3   state             2 non-null      object
 4   type              2 non-null      object
 5   technician_count  2 non-null      int64
 6   maintenance_bays  2 non-null      int64
dtypes: int64(2), object(5)
memory usage: 244.0+ bytes

============================================================
  dim_aircraft
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   aircraft_id          62 non-null     object
 1   tail_number          62 non-null     object
 2   model                62 non-null     object
 3   engine_type          62 non-null     object
 4   engine_count         62 non-null     int64
 5   serial_number        62 non-null     object
 6   delivery_date        62 non-null     object
 7   years_in_service     62 non-null     float64
 8   base_facility_id     62 non-null     object
 9   region               62 non-null     object
 10  seat_capacity        62 non-null     int64
 11  max_range_nm         62 non-null     int64
 12  mtow_kg              62 non-null     int64
 13  current_status       62 non-null     object
 14  maintenance_program  62 non-null     object
dtypes: float64(1), int64(4), object(10)
memory usage: 7.4+ KB

============================================================
  dim_crew
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   crew_id           120 non-null    object
 1   crew_name         120 non-null    object
 2   role              120 non-null    object
 3   base_facility_id  120 non-null    object
 4   type_ratings      120 non-null    object
dtypes: object(5)
memory usage: 4.8+ KB

============================================================
  fact_flight
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142841 entries, 0 to 142840
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   flight_id             142841 non-null  object
 1   date                  142841 non-null  object
 2   aircraft_id           142841 non-null  object
 3   tail_number           142841 non-null  object
 4   model                 142841 non-null  object
 5   owner_id              117677 non-null  object
 6   booking_id            117677 non-null  object
 7   journey_leg_seq       142841 non-null  int64
 8   origin_icao           142841 non-null  object
 9   destination_icao      142841 non-null  object
 10  departure_time        142841 non-null  object
 11  arrival_time          142841 non-null  object
 12  block_hours           142841 non-null  float64
 13  flight_hours          142841 non-null  float64
 14  distance_nm           142841 non-null  int64
 15  passenger_count       142841 non-null  int64
 16  flight_purpose        142841 non-null  object
 17  is_deadhead           142841 non-null  int64
 18  is_maintenance_ferry  142841 non-null  int64
 19  flight_status         142841 non-null  object
 20  fuel_consumed_gal     142841 non-null  float64
 21  weather_delay_min     142841 non-null  int64
 22  pilot_id              142841 non-null  object
 23  copilot_id            64215 non-null   object
 24  season                142841 non-null  object
 25  day_of_week           142841 non-null  int64
dtypes: float64(3), int64(7), object(16)
memory usage: 28.3+ MB

============================================================
  fact_aircraft_daily_status
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63080 entries, 0 to 63079
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aircraft_id       63080 non-null  object
 1   date              63080 non-null  object
 2   status            63080 non-null  object
 3   flight_hours      63080 non-null  float64
 4   flight_cycles     63080 non-null  int64
 5   maintenance_type  4546 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.9+ MB

============================================================
  fact_maintenance_job
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589 entries, 0 to 2588
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   maintenance_job_id       2589 non-null   object
 1   date                     2589 non-null   object
 2   aircraft_id              2589 non-null   object
 3   tail_number              2589 non-null   object
 4   facility_id              2589 non-null   object
 5   maintenance_type         2589 non-null   object
 6   is_scheduled             2589 non-null   int64
 7   severity                 2589 non-null   object
 8   trigger_source           2589 non-null   object
 9   job_status               2589 non-null   object
 10  start_datetime           2589 non-null   object
 11  close_datetime           2574 non-null   object
 12  total_elapsed_hours      2574 non-null   float64
 13  finding_code             2589 non-null   object
 14  technician_id            2589 non-null   object
 15  aircraft_hours_at_event  2589 non-null   float64
dtypes: float64(2), int64(1), object(13)
memory usage: 323.8+ KB

============================================================
  dim_component
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   component_id      44 non-null     object
 1   jasc_ata_code     44 non-null     int64
 2   system_name       44 non-null     object
 3   component_name    44 non-null     object
 4   sdrs_weight_pc12  44 non-null     float64
 5   sdrs_weight_pc24  44 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 2.2+ KB

============================================================
  dim_date
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date_key         1096 non-null   int64
 1   date             1096 non-null   object
 2   day              1096 non-null   int64
 3   day_of_week      1096 non-null   object
 4   day_of_week_num  1096 non-null   int64
 5   is_weekend       1096 non-null   int64
 6   week_num         1096 non-null   int64
 7   month            1096 non-null   int64
 8   month_name       1096 non-null   object
 9   quarter          1096 non-null   int64
 10  year             1096 non-null   int64
 11  season           1096 non-null   object
 12  is_holiday       1096 non-null   int64
 13  fiscal_year      1096 non-null   int64
dtypes: int64(10), object(4)
memory usage: 120.0+ KB

============================================================
  dim_owner
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   owner_id                 350 non-null    object
 1   owner_name               350 non-null    object
 2   region                   350 non-null    object
 3   state                    350 non-null    object
 4   share_type               350 non-null    object
 5   annual_hours_contracted  350 non-null    int64
 6   join_date                350 non-null    object
 7   tenure_years             350 non-null    float64
 8   aircraft_preference      350 non-null    object
 9   cobalt_pass_holder       350 non-null    int64
 10  jetfly_access            350 non-null    int64
 11  status                   350 non-null    object
 12  owner_type               350 non-null    object
dtypes: float64(1), int64(3), object(9)
memory usage: 35.7+ KB

============================================================
  fact_booking
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123560 entries, 0 to 123559
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   booking_id        123560 non-null  object
 1   booking_date      123560 non-null  object
 2   owner_id          123560 non-null  object
 3   passenger_count   123560 non-null  int64
 4   pet_count         123560 non-null  int64
 5   preferred_model   123560 non-null  object
 6   departure_date    123560 non-null  object
 7   origin_icao       123560 non-null  object
 8   destination_icao  123560 non-null  object
 9   trip_purpose      123560 non-null  object
 10  booking_status    123560 non-null  object
 11  booking_channel   123560 non-null  object
 12  lead_time_days    123560 non-null  int64
dtypes: int64(3), object(10)
memory usage: 12.3+ MB

============================================================
  dim_airport
============================================================

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airport_icao      34 non-null     object
 1   airport_name      34 non-null     object
 2   city              34 non-null     object
 3   state             34 non-null     object
 4   region            34 non-null     object
 5   runway_length_ft  34 non-null     int64
 6   runway_surface    34 non-null     object
 7   pc12_accessible   34 non-null     int64
 8   pc24_accessible   34 non-null     int64
 9   latitude          34 non-null     float64
 10  longitude         34 non-null     float64
dtypes: float64(2), int64(3), object(6)
memory usage: 3.1+ KB

In [6]:
dfs.keys()

dict_keys(['fact_maintenance_detail', 'dim_facility', 'dim_aircraft', 'dim_crew', 'fact_flight', 'fact_aircraft_daily_status', 'fact_maintenance_job', 'dim_component', 'dim_date', 'dim_owner', 'fact_booking', 'dim_airport'])

In [7]:
fact_aircraft_daily_status

,aircraft_id,date,status,flight_hours,flight_cycles,maintenance_type
0,AC-001,1/1/23,FLYING,2.52,2,NaN
1,AC-001,1/2/23,FLYING,1.64,2,NaN
2,AC-001,1/3/23,FLYING,2.71,2,NaN
3,AC-001,1/4/23,FLYING,3.18,3,NaN
4,AC-001,1/5/23,FLYING,2.89,2,NaN
...,...,...,...,...,...,...
63075,AC-062,12/27/25,FLYING,2.87,2,NaN
63076,AC-062,12/28/25,FLYING,3.44,2,NaN
63077,AC-062,12/29/25,AVAILABLE,0.00,0,NaN
63078,AC-062,12/30/25,FLYING,5.80,4,NaN
63079,AC-062,12/31/25,FLYING,2.81,2,NaN

In [8]:
fact_aircraft_daily_status.status.value_counts()

status
FLYING            52919
AVAILABLE          5615
IN_MAINTENANCE     4483
AOG                  63
Name: count, dtype: int64

In [9]:
fact_flight

,flight_id,date,aircraft_id,tail_number,model,owner_id,booking_id,journey_leg_seq,origin_icao,destination_icao,...,flight_purpose,is_deadhead,is_maintenance_ferry,flight_status,fuel_consumed_gal,weather_delay_min,pilot_id,copilot_id,season,day_of_week
0,FLT-0000001,2023-01-01,AC-001,N100AF,PC-12 NGX,OWN-0005,BK-0000001,1,KJFK,KPWM,...,Leisure,0,0,COMPLETED,59.8,0,CREW-015,NaN,Winter,7
1,FLT-0000002,2023-01-01,AC-001,N100AF,PC-12 NGX,NaN,NaN,1,KSFM,KPSM,...,Repositioning,1,0,COMPLETED,4.8,0,CREW-070,NaN,Winter,7
2,FLT-0000003,2023-01-02,AC-001,N100AF,PC-12 NGX,OWN-0307,BK-0000003,1,KBED,KTEB,...,Business,0,0,COMPLETED,40.1,0,CREW-069,CREW-009,Winter,1
3,FLT-0000004,2023-01-02,AC-001,N100AF,PC-12 NGX,OWN-0247,BK-0000004,1,KPSM,KBDL,...,Business,0,0,COMPLETED,27.2,0,CREW-010,NaN,Winter,1
4,FLT-0000005,2023-01-03,AC-001,N100AF,PC-12 NGX,OWN-0246,BK-0000005,1,KPWM,KMVY,...,Leisure,0,0,COMPLETED,34.0,0,CREW-041,CREW-016,Winter,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142836,FLT-0142837,2025-12-30,AC-062,N815AF,PC-24,OWN-0259,BK-0142837,1,KEWR,KJFK,...,Business,0,0,COMPLETED,4.8,0,CREW-051,CREW-032,Winter,2
142837,FLT-0142838,2025-12-30,AC-062,N815AF,PC-24,NaN,NaN,1,KSFM,KPSM,...,Repositioning,1,0,COMPLETED,5.7,0,CREW-068,CREW-035,Winter,2
142838,FLT-0142839,2025-12-30,AC-062,N815AF,PC-24,OWN-0241,BK-0142839,1,KMVY,KPBI,...,Leisure,0,0,COMPLETED,279.3,0,CREW-022,CREW-009,Winter,2
142839,FLT-0142840,2025-12-31,AC-062,N815AF,PC-24,OWN-0326,BK-0142840,1,KATL,KJFK,...,Medical,0,0,COMPLETED,184.3,0,CREW-072,CREW-043,Winter,3
142840,FLT-0142841,2025-12-31,AC-062,N815AF,PC-24,OWN-0023,BK-0142841,1,KBOS,KTPA,...,Business,0,0,COMPLETED,287.8,0,CREW-007,CREW-074,Winter,3

In [10]:
fact_flight.origin_icao.value_counts()

origin_icao
KPSM    19941
KBDL     9559
KBED     9018
KPVD     8694
KJFK     7342
KBOS     7313
KEWR     7249
KTEB     6690
KHPN     6615
KIAD     6419
KPHL     6393
KACK     5134
KSFM     5046
KPWM     4960
KMVY     4958
2B2      4167
K1B1     4126
KMHT     2248
KBVU     1978
KTPA     1565
KMIA     1555
KFLL     1555
KATL     1272
KPBI     1214
KORD     1172
KCLT     1169
KMSP     1110
KAPC      679
KSFO      638
KDEN      623
KSAN      623
KLAX      609
KSDM      607
KLAS      600
Name: count, dtype: int64

In [11]:
fact_flight.destination_icao.value_counts()

destination_icao
KBDL    10946
KBED     9615
KPVD     9484
KBOS     7972
KJFK     7942
KEWR     7763
KHPN     7152
KTEB     7151
KPHL     6934
KIAD     6924
KPSM     6702
KPWM     5974
KMVY     5480
KSFM     5447
KACK     5438
2B2      4514
K1B1     4392
KCLT     3159
KMHT     2857
KORD     2268
KATL     1783
KFLL     1541
KTPA     1516
KMIA     1435
KBVU     1406
KLAS     1153
KPBI     1119
KDEN      915
KMSP      909
KSAN      626
KSDM      616
KLAX      582
KAPC      580
KSFO      546
Name: count, dtype: int64

In [12]:
fact_flight.flight_purpose.value_counts()

flight_purpose
Business             64882
Leisure              33018
Repositioning        20811
Mixed                13998
Medical               5779
Maintenance Ferry     4353
Name: count, dtype: int64

In [13]:
fact_maintenance_job

,maintenance_job_id,date,aircraft_id,tail_number,facility_id,maintenance_type,is_scheduled,severity,trigger_source,job_status,start_datetime,close_datetime,total_elapsed_hours,finding_code,technician_id,aircraft_hours_at_event
0,MJ-000001,1/19/23,AC-001,N100AF,FAC-PSM,COMPONENT_REPLACEMENT,0,MODERATE,PILOT_REPORT,COMPLETED,1/19/23 20:00,1/20/23 8:29,12.5,Engine (General),TECH-025,50.8
1,MJ-000002,2/8/23,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2/8/23 7:00,2/8/23 17:13,10.2,NO_FINDING,TECH-030,100.3
2,MJ-000003,3/22/23,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,3/22/23 7:00,3/22/23 19:16,12.3,NO_FINDING,TECH-025,200.5
3,MJ-000004,3/22/23,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,3/22/23 7:00,3/23/23 13:13,30.2,NO_FINDING,TECH-012,200.5
4,MJ-000005,5/3/23,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,5/3/23 7:00,5/3/23 20:32,13.5,REPLACEMENT_REQUIRED,TECH-007,301.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2584,MJ-002585,9/20/25,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,9/20/25 7:00,9/21/25 5:04,22.1,MINOR_DEFECT,TECH-038,2814.0
2585,MJ-002586,9/23/25,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,9/23/25 7:00,9/23/25 22:39,15.7,WEAR_WITHIN_LIMITS,TECH-015,2820.5
2586,MJ-002587,11/3/25,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,11/3/25 7:00,11/3/25 16:05,9.1,NO_FINDING,TECH-009,2922.3
2587,MJ-002588,12/10/25,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,12/10/25 7:00,12/11/25 10:16,27.3,NO_FINDING,TECH-014,3015.7
2588,MJ-002589,12/13/25,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,12/13/25 7:00,12/14/25 1:43,18.7,MINOR_DEFECT,TECH-002,3023.8

In [14]:
fact_maintenance_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589 entries, 0 to 2588
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   maintenance_job_id       2589 non-null   object
 1   date                     2589 non-null   object
 2   aircraft_id              2589 non-null   object
 3   tail_number              2589 non-null   object
 4   facility_id              2589 non-null   object
 5   maintenance_type         2589 non-null   object
 6   is_scheduled             2589 non-null   int64
 7   severity                 2589 non-null   object
 8   trigger_source           2589 non-null   object
 9   job_status               2589 non-null   object
 10  start_datetime           2589 non-null   object
 11  close_datetime           2574 non-null   object
 12  total_elapsed_hours      2574 non-null   float64
 13  finding_code             2589 non-null   object
 14  technician_id            2589 non-null   object
 15  aircraft_hours_at_event  2589 non-null   float64
dtypes: float64(2), int64(1), object(13)
memory usage: 323.8+ KB

In [15]:
import pandas as pd

def infer_and_set_dtypes(df):
    df = df.copy()
    
    for col in df.columns:
        # Skip if already numeric or datetime
        if pd.api.types.is_numeric_dtype(df[col]) or pd.api.types.is_datetime64_any_dtype(df[col]):
            continue
        
        # Try datetime conversion
        try:
            converted = pd.to_datetime(df[col], errors='raise')
            df[col] = converted
            continue
        except:
            pass
        
        # Try numeric conversion
        try:
            converted = pd.to_numeric(df[col], errors='raise')
            
            # Check if integer
            if (converted.dropna() % 1 == 0).all():
                df[col] = converted.astype("Int64")  # nullable integer
            else:
                df[col] = converted.astype(float)
                
        except:
            # Leave as string
            df[col] = df[col].astype("string")
    
    return df

In [16]:
fact_maintenance_job = infer_and_set_dtypes(fact_maintenance_job)

/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')
/var/folders/n7/7cb0sm8s3hd6kqn4m0thhbpc0000gn/T/ipykernel_47303/290248774.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  converted = pd.to_datetime(df[col], errors='raise')

In [17]:
fact_maintenance_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589 entries, 0 to 2588
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   maintenance_job_id       2589 non-null   string
 1   date                     2589 non-null   datetime64[ns]
 2   aircraft_id              2589 non-null   string
 3   tail_number              2589 non-null   string
 4   facility_id              2589 non-null   string
 5   maintenance_type         2589 non-null   string
 6   is_scheduled             2589 non-null   int64
 7   severity                 2589 non-null   string
 8   trigger_source           2589 non-null   string
 9   job_status               2589 non-null   string
 10  start_datetime           2589 non-null   datetime64[ns]
 11  close_datetime           2574 non-null   datetime64[ns]
 12  total_elapsed_hours      2574 non-null   float64
 13  finding_code             2589 non-null   string
 14  technician_id            2589 non-null   string
 15  aircraft_hours_at_event  2589 non-null   float64
dtypes: datetime64[ns](3), float64(2), int64(1), string(10)
memory usage: 323.8 KB

In [18]:
def create_month_column(df, datetime_col, new_col="month", format_type="yyyymm"):
    
    df = df.copy()
    df[datetime_col] = pd.to_datetime(df[datetime_col], errors="coerce")
    
    if format_type == "yyyymm":
        df[new_col] = df[datetime_col].dt.year * 100 + df[datetime_col].dt.month
        
    elif format_type == "period":
        df[new_col] = df[datetime_col].dt.to_period("M")
        
    elif format_type == "string":
        df[new_col] = df[datetime_col].dt.strftime("%Y%m")
        
    else:
        raise ValueError("format_type must be 'yyyymm', 'period', or 'string'")
        
    return df

In [19]:
fact_maintenance_job = create_month_column(fact_maintenance_job, "close_datetime", "close_month", "period")

In [20]:
fact_maintenance_job.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589 entries, 0 to 2588
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   maintenance_job_id       2589 non-null   string
 1   date                     2589 non-null   datetime64[ns]
 2   aircraft_id              2589 non-null   string
 3   tail_number              2589 non-null   string
 4   facility_id              2589 non-null   string
 5   maintenance_type         2589 non-null   string
 6   is_scheduled             2589 non-null   int64
 7   severity                 2589 non-null   string
 8   trigger_source           2589 non-null   string
 9   job_status               2589 non-null   string
 10  start_datetime           2589 non-null   datetime64[ns]
 11  close_datetime           2574 non-null   datetime64[ns]
 12  total_elapsed_hours      2574 non-null   float64
 13  finding_code             2589 non-null   string
 14  technician_id            2589 non-null   string
 15  aircraft_hours_at_event  2589 non-null   float64
 16  close_month              2574 non-null   period[M]
dtypes: datetime64[ns](3), float64(2), int64(1), period[M](1), string(10)
memory usage: 344.0 KB

In [21]:
fact_maintenance_job

,maintenance_job_id,date,aircraft_id,tail_number,facility_id,maintenance_type,is_scheduled,severity,trigger_source,job_status,start_datetime,close_datetime,total_elapsed_hours,finding_code,technician_id,aircraft_hours_at_event,close_month
0,MJ-000001,2023-01-19,AC-001,N100AF,FAC-PSM,COMPONENT_REPLACEMENT,0,MODERATE,PILOT_REPORT,COMPLETED,2023-01-19 20:00:00,2023-01-20 08:29:00,12.5,Engine (General),TECH-025,50.8,2023-01
1,MJ-000002,2023-02-08,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2023-02-08 07:00:00,2023-02-08 17:13:00,10.2,NO_FINDING,TECH-030,100.3,2023-02
2,MJ-000003,2023-03-22,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2023-03-22 07:00:00,2023-03-22 19:16:00,12.3,NO_FINDING,TECH-025,200.5,2023-03
3,MJ-000004,2023-03-22,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2023-03-22 07:00:00,2023-03-23 13:13:00,30.2,NO_FINDING,TECH-012,200.5,2023-03
4,MJ-000005,2023-05-03,AC-001,N100AF,FAC-PSM,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2023-05-03 07:00:00,2023-05-03 20:32:00,13.5,REPLACEMENT_REQUIRED,TECH-007,301.0,2023-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2584,MJ-002585,2025-09-20,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2025-09-20 07:00:00,2025-09-21 05:04:00,22.1,MINOR_DEFECT,TECH-038,2814.0,2025-09
2585,MJ-002586,2025-09-23,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2025-09-23 07:00:00,2025-09-23 22:39:00,15.7,WEAR_WITHIN_LIMITS,TECH-015,2820.5,2025-09
2586,MJ-002587,2025-11-03,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2025-11-03 07:00:00,2025-11-03 16:05:00,9.1,NO_FINDING,TECH-009,2922.3,2025-11
2587,MJ-002588,2025-12-10,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2025-12-10 07:00:00,2025-12-11 10:16:00,27.3,NO_FINDING,TECH-014,3015.7,2025-12
2588,MJ-002589,2025-12-13,AC-062,N815AF,FAC-BVU,INSPECTION,1,ROUTINE,SCHEDULED,COMPLETED,2025-12-13 07:00:00,2025-12-14 01:43:00,18.7,MINOR_DEFECT,TECH-002,3023.8,2025-12

In [22]:
fact_maintenance_job.close_month.value_counts()

close_month
2024-07    116
2023-06     99
2025-08     96
2023-08     93
2025-03     93
2025-06     92
2025-07     89
2024-12     87
2024-05     84
2024-10     82
2024-09     81
2025-11     81
2023-11     81
2025-05     81
2025-10     77
2025-09     75
2024-08     75
2024-04     73
2024-06     71
2024-01     68
2023-03     68
2025-01     67
2025-04     65
2024-02     63
2023-07     63
2025-02     60
2024-03     60
2023-10     60
2023-05     58
2023-12     57
2024-11     57
2023-09     54
2025-12     52
2023-02     50
2023-04     41
2023-01      5
Freq: M, Name: count, dtype: int64

In [23]:
fact_maintenance_job.maintenance_type.value_counts()

maintenance_type
INSPECTION               2362
LINE_MAINTENANCE           91
COMPONENT_REPLACEMENT      75
TROUBLESHOOTING            43
AOG_REPAIR                 18
Name: count, dtype: Int64

In [25]:
fact_flight.columns

Index(['flight_id', 'date', 'aircraft_id', 'tail_number', 'model', 'owner_id',
       'booking_id', 'journey_leg_seq', 'origin_icao', 'destination_icao',
       'departure_time', 'arrival_time', 'block_hours', 'flight_hours',
       'distance_nm', 'passenger_count', 'flight_purpose', 'is_deadhead',
       'is_maintenance_ferry', 'flight_status', 'fuel_consumed_gal',
       'weather_delay_min', 'pilot_id', 'copilot_id', 'season', 'day_of_week'],
      dtype='object')

In [26]:
fact_flight.flight_hours

0         0.88
1         0.07
2         0.59
3         0.40
4         0.50
          ...
142836    0.05
142837    0.06
142838    2.94
142839    1.94
142840    3.03
Name: flight_hours, Length: 142841, dtype: float64